resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: tahsin/git-pull-resource
    tag: latest

resources:
- name: digitalocean
  type: pull-request
  source:
    owner: pharmer
    repo: pharmer
    label: cloud/digitalocean
    access_token: ((access_token))

jobs:
- name: digitalocean
  plan:
  - get: digitalocean
    trigger: true
  - put: digitalocean
    params: { path: digitalocean, status: pending}
  - task: test
    file: digitalocean/hack/concourse/task.yml
    input_mapping:
      pharmer: digitalocean
    params:
      CredProvider: DigitalOcean
      ClusterProvider: digitalocean
      TOKEN: ((digitaloceanToken))
    on_success:
      put: digitalocean
      params: { path: digitalocean, status: success }
    on_failure:
      put: digitalocean
      params: {path: digitalocean, status: failure }

